import type { Metadata } from "next";
import "../app/ui/global.css";
import "bootstrap/dist/css/bootstrap.min.css"
import BootstrapJs from "../app/bootstrapJs"
import FontAwesomeConfig from "../app/ui/fontawesome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body>
        {children}
      </body>
      <BootstrapJs />
    </html>
  );
}
